/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.standalone.gui.vista;

import javax.naming.NamingException;
import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.pa.persistencia.modelo.entidades.Docente;
import co.edu.eam.ingesoft.standalone.gui.controlador.ControladorVentanaDocente;

/**
 *
 * @author caferrer
 */
public class Ventana extends javax.swing.JFrame {

	/**
	 * controlador.
	 */
	private ControladorVentanaDocente controlador;

	/**
	 * Creates new form Ventana
	 */
	public Ventana() {
		initComponents();
		try {
			controlador = new ControladorVentanaDocente();
		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		tfIdent = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		tfNom = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		tfApellido = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		tfEmail = new javax.swing.JTextField();
		bCrear = new javax.swing.JButton();
		bBuscar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel1.setText("identificacion");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel2.setText("Nombre");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel3.setText("Apellido");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel4.setText("Email");

		bCrear.setText("Crear");
		bCrear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bCrearActionPerformed(evt);
			}
		});

		bBuscar.setText("Buscar");
		bBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bBuscarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGap(32, 32, 32).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel4).addGap(68, 68, 68)
										.addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1).addGap(18, 18, 18)
										.addComponent(tfIdent))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel2).addGap(52, 52, 52)
										.addComponent(tfNom))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel3).addGap(50, 50, 50)
										.addComponent(tfApellido))))
						.addGroup(layout.createSequentialGroup().addGap(78, 78, 78)
								.addComponent(bCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(26, 26, 26).addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(37, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(37, 37, 37)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(tfIdent, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(36, 36, 36)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(bCrear).addComponent(bBuscar))
						.addContainerGap(60, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			Docente doc = new Docente();
			doc.setApellido(tfApellido.getText());
			doc.setCorreoelectronico(tfEmail.getText());
			doc.setDocumentoidentificacion(tfIdent.getText());
			doc.setNombre(tfNom.getText());

			controlador.crearDocente(doc);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {

		// TODO add your handling code here:
		try {
			

			Docente doc=controlador.buscarDocente(tfIdent.getText());
			if(doc!=null){
				tfNom.setText(doc.getNombre());
				tfApellido.setText(doc.getApellido());
				tfEmail.setText(doc.getCorreoelectronico());
			}else{
				JOptionPane.showMessageDialog(null, "No existe!!!!", "ERROR", JOptionPane.WARNING_MESSAGE);
			}
			
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Ventana().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton bBuscar;
	private javax.swing.JButton bCrear;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField tfApellido;
	private javax.swing.JTextField tfEmail;
	private javax.swing.JTextField tfIdent;
	private javax.swing.JTextField tfNom;
	// End of variables declaration
}
